# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cr_enum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cr_enum.proto',
  package='cr_enum',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rcr_enum.proto\x12\x07\x63r_enum*D\n\x12\x65num_scenario_type\x12\x11\n\rall_scenarios\x10\x00\x12\r\n\tsandtable\x10\x01\x12\x0c\n\x08topology\x10\x02*w\n\x0f\x65num_panel_type\x12\x0e\n\nall_panels\x10\x00\x12\x0e\n\nscoreboard\x10\x01\x12\r\n\tevent_log\x10\x02\x12\x0b\n\x07netflow\x10\x03\x12\x10\n\x0c\x64\x65vice_panel\x10\x04\x12\x16\n\x12top_director_panel\x10\x05*d\n\x10\x65num_effect_icon\x12\x0b\n\x07no_icon\x10\x00\x12\x0f\n\x0b\x65xclamation\x10\x01\x12\x0f\n\x0binformation\x10\x02\x12\x0c\n\x08question\x10\x03\x12\n\n\x06wrench\x10\x04\x12\x07\n\x03\x63og\x10\x05*t\n\x15\x65num_attack_intensity\x12\x0f\n\x0b\x61ttack_weak\x10\x00\x12\x13\n\x0f\x61ttack_moderate\x10\x01\x12\x10\n\x0c\x61ttack_heavy\x10\x02\x12\x12\n\x0e\x61ttack_extreme\x10\x03\x12\x0f\n\x0b\x61ttack_epic\x10\x04\x62\x06proto3')
)

_ENUM_SCENARIO_TYPE = _descriptor.EnumDescriptor(
  name='enum_scenario_type',
  full_name='cr_enum.enum_scenario_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='all_scenarios', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sandtable', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='topology', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=26,
  serialized_end=94,
)
_sym_db.RegisterEnumDescriptor(_ENUM_SCENARIO_TYPE)

enum_scenario_type = enum_type_wrapper.EnumTypeWrapper(_ENUM_SCENARIO_TYPE)
_ENUM_PANEL_TYPE = _descriptor.EnumDescriptor(
  name='enum_panel_type',
  full_name='cr_enum.enum_panel_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='all_panels', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='scoreboard', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='event_log', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='netflow', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='device_panel', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='top_director_panel', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=96,
  serialized_end=215,
)
_sym_db.RegisterEnumDescriptor(_ENUM_PANEL_TYPE)

enum_panel_type = enum_type_wrapper.EnumTypeWrapper(_ENUM_PANEL_TYPE)
_ENUM_EFFECT_ICON = _descriptor.EnumDescriptor(
  name='enum_effect_icon',
  full_name='cr_enum.enum_effect_icon',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='no_icon', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='exclamation', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='information', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='question', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='wrench', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='cog', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=217,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_ENUM_EFFECT_ICON)

enum_effect_icon = enum_type_wrapper.EnumTypeWrapper(_ENUM_EFFECT_ICON)
_ENUM_ATTACK_INTENSITY = _descriptor.EnumDescriptor(
  name='enum_attack_intensity',
  full_name='cr_enum.enum_attack_intensity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='attack_weak', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='attack_moderate', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='attack_heavy', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='attack_extreme', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='attack_epic', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=319,
  serialized_end=435,
)
_sym_db.RegisterEnumDescriptor(_ENUM_ATTACK_INTENSITY)

enum_attack_intensity = enum_type_wrapper.EnumTypeWrapper(_ENUM_ATTACK_INTENSITY)
all_scenarios = 0
sandtable = 1
topology = 2
all_panels = 0
scoreboard = 1
event_log = 2
netflow = 3
device_panel = 4
top_director_panel = 5
no_icon = 0
exclamation = 1
information = 2
question = 3
wrench = 4
cog = 5
attack_weak = 0
attack_moderate = 1
attack_heavy = 2
attack_extreme = 3
attack_epic = 4


DESCRIPTOR.enum_types_by_name['enum_scenario_type'] = _ENUM_SCENARIO_TYPE
DESCRIPTOR.enum_types_by_name['enum_panel_type'] = _ENUM_PANEL_TYPE
DESCRIPTOR.enum_types_by_name['enum_effect_icon'] = _ENUM_EFFECT_ICON
DESCRIPTOR.enum_types_by_name['enum_attack_intensity'] = _ENUM_ATTACK_INTENSITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
